language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
dist: trusty
sudo: true
before_install:
  - gem update --system
  - gem install bundler -v 1.16.2
cache: bundler
